import {  Share_Tech_Mono, Kanit } from "next/font/google";
import "./globals.css";

const shareTechMono = Share_Tech_Mono({
  subsets: ['latin'],
  weight: '400', 
})

const kanit = Kanit ({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${shareTechMono.variable} ${kanit.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
